### PR TITLE
Modifications Contract

### PR DESCRIPTION
**Pull request by antoineroson**
We’ve modified the interface contract and lines which referred to this interface in other package do we need the ok from other groups impacted ?

### CODE REVIEW

**Comment by antoineroson** [comment]
@AnaisBel @theostourm @aprage16

**Comment by AnaisBel** [comment]
Producteur Amérique latine ok

Envoyé de mon iPhone

**Comment by theostourm** [comment]
Ok from transformateur europe

**Comment by massimotisi** [comment]
yes, I need the OK from @CACAO2017/transformateur-usa too

**Comment by aprage16** [comment]
ok for transformateur usa

**Pull request merged**
