### PR TITLE
modif transfo usa

### PR DESCRIPTION
**Pull request by aprage16**
modifications

### CODE REVIEW

**Comment by massimotisi** [comment]
To solve:
- errors in `.gitignore`
- compile-time errors in `CACAO2017/src/abstraction/distributeur/europe/MondeV1.java`
- need OK from @CACAO2017/distributeur-europe

**Comment by wowalid** [comment]
Ok

**Comment by aprage16** [comment]
@massimotisi i don't understand where we are involved in these errors

I don't find .gitignore

**Comment by massimotisi** [comment]
* I have fixed the .gitignore problem on your repository (please sync to see the change on your computer).
* As you can see here https://github.com/CACAO2017/CACAO2017/pull/41/files your pull request wants to remove all the content from the Marche class of @CACAO2017/distributeur-europe. This causes the errors.

**Comment by massimotisi** [comment]
I suggest you to compare the `CACAO2017/src/abstraction/distributeur/europe/Marche.java` file in your Eclipse with the one on the main repository: https://github.com/CACAO2017/CACAO2017/blob/master/CACAO2017/src/abstraction/distributeur/europe/Marche.java

**Comment by aprage16** [comment]
@massimotisi We had problems to update the code with github so we changed some parts of the code before merging with the other groups. That’s why we don’t have the same code than the others and this causes errors.





De : Massimo Tisi
Envoyé : ‎jeudi‎ ‎11‎ ‎mai‎ ‎2017 ‎13‎:‎26
À : CACAO2017/CACAO2017
Cc : aprage16, Author




I have fixed the .gitignore problem on your repository (please sync to see the change on your computer).
As you can see here https://github.com/CACAO2017/CACAO2017/pull/41/files your pull request wants to remove all the content from the Marche class of @CACAO2017/distributeur-europe. This causes the errors.

**Comment by massimotisi** [comment]
As I said, the compile-time error (red error in Eclipse) depends only on the fact that you removed the content of the class `CACAO2017/src/abstraction/distributeur/europe/Marche.java`. Please substitute it with the version that everybody else has (https://github.com/CACAO2017/CACAO2017/blob/master/CACAO2017/src/abstraction/distributeur/europe/Marche.java) and it should be fine.

**Comment by aprage16** [comment]
We have deleted and reforked the project on github and we will do a new merged with a good code @massimotisi





De : Massimo Tisi
Envoyé : ‎jeudi‎ ‎11‎ ‎mai‎ ‎2017 ‎13‎:‎44
À : CACAO2017/CACAO2017
Cc : aprage16, Author





As I said, the compile-time error (red error in Eclipse) depends only on the fact that you removed the content of the class CACAO2017/src/abstraction/distributeur/europe/Marche.java. Please substitute it with the version that everybody else has (https://github.com/CACAO2017/CACAO2017/blob/master/CACAO2017/src/abstraction/distributeur/europe/Marche.java) and it should be fine.

**Comment by massimotisi** [comment]
If you agree I will close this pull request and wait for a new one.

**Pull request closed without merging**
