### PR TITLE
Début du marché client

### PR DESCRIPTION
**Pull request by danjud**

### CODE REVIEW

**Comment by massimotisi** [comment]
need OK from @CACAO2017/distributeur-europe

**Comment by danjud** [comment]
It should be ok now, it doesn't affect them anymore

**Comment by wowalid** [comment]
OK

**Comment by massimotisi** [comment]
`Exception in thread "main" java.lang.NullPointerException
	at presentation.FenetrePrincipale.<init>(FenetrePrincipale.java:66)
	at presentation.FenetrePrincipale.main(FenetrePrincipale.java:146)
`

**Comment by massimotisi** [comment]
If you are looking for the cause of the exception, I would start from `prixMax`.

**Comment by danjud** [comment]
Should be ok now

**Pull request merged**
