### PR TITLE
Creation contrats

### PR DESCRIPTION
**Pull request by antoineroson**

### CODE REVIEW

**Comment by massimotisi** [comment]
I propose you to move the package `CACAO2017/src/abstraction/contrats` to `CACAO2017/src/abstraction/producteur/cotedivoire/contrats`

**Comment by antoineroson** [comment]
@prod_Cotedivoire is the "manager" of this package. OK from Romu for this.

**Comment by massimotisi** [comment]
After discussion with @romucsp we decided that it's better to move the package to `CACAO2017/src/abstraction/producteur/cotedivoire/contrats`

**Comment by antoineroson** [comment]
Is it ok like this ?

**Comment by massimotisi** [comment]
Actually we were proposing to create a `contract` package *inside* the `cotedivoire` package.

**Comment by antoineroson** [comment]
I tried but it doesn't work, we i click on my package and (right) as if i wanted to create a new class in my package and click on new package, the new package created is put under src...

**Comment by massimotisi** [comment]
This is normal, you just need to be sure that the complete name of the package is: `abstraction.producteur.cotedivoire.contrats`

**Comment by antoineroson** [comment]
is that correct?

**Comment by massimotisi** [comment]
OK

**Pull request merged**
