### PR TITLE
changements interfaces marché

### PR DESCRIPTION
**Pull request by aprage16**
dissociation de l'interface transformateur, en deux interfaces : une pour le marché distributeur et une pour le marché producteur

### CODE REVIEW

**Comment by massimotisi** [comment]
Compilation error!!

**Comment by aprage16** [comment]
Yes, but only in MondeV1, because @wowalid will have to modify his code with the new interfaces' names
@massimotisi

**Comment by massimotisi** [comment]
As you know, I will never merge any compilation error. By collaborating with @wowalid, you can fix the other package too. @wowalid will have to explicitly give his OK before merging.

**Comment by aprage16** [comment]
ok, we will fix it soon then

**Comment by aprage16** [comment]
we have done some changes, with @wowalid , we have changed some class of producteur cote d'ivoire and transformateur europe too

**Comment by massimotisi** [comment]
I need the OK from @CACAO2017/transformateur-europe @CACAO2017/producteur-cotedivoire and @CACAO2017/distributeur-europe

**Comment by wowalid** [comment]
OK

**Comment by antoineroson** [comment]
OK from ProdCôted'iv

**Comment by theostourm** [comment]
Ok from transfo europe

**Pull request merged**
