### PR TITLE
Master

### PR DESCRIPTION
**Pull request by wowalid**
Ajout de l'acteur AgentContrat dans le MondeV1

### CODE REVIEW

**Comment by massimotisi** [comment]
There is a NullPointerException

**Comment by massimotisi** [comment]
Any news on this?

**Comment by wowalid** [comment]
it should be ok

**Comment by antoineroson** [comment]
OK

[Approved with PullApprove](https://pullapprove.com/CACAO2017/CACAO2017/pull-request/87/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=CACAO2017/CACAO2017)

**Comment by AnaisBel** [comment]
OK

[Approved with PullApprove](https://pullapprove.com/CACAO2017/CACAO2017/pull-request/87/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=CACAO2017/CACAO2017)

**Comment by massimotisi** [comment]
Still a conflict on CACAO2017/src/abstraction/distributeur/europe/MondeV1.java

**Comment by massimotisi** [comment]
OK


[Approved with PullApprove](https://pullapprove.com/CACAO2017/CACAO2017/pull-request/87/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=CACAO2017/CACAO2017)

**Pull request merged**
