### PR TITLE
Master

### PR DESCRIPTION
**Pull request by theostourm**
V1

### CODE REVIEW

**Comment by massimotisi** [comment]
- Please do not modify `CACAO2017/src/abstraction/transformateur/usa/TransformateurUsa.java` and `CACAO2017/src/presentation/FenetreJournal.java`
- Needs the OK from @CACAO2017/distributeur-europe

**Comment by wowalid** [comment]
ok

**Comment by massimotisi** [comment]
After accepting the pull request from @CACAO2017/distributeur-europe, this one conflicts. Please update from my repository and solve the conflict.

**Comment by theostourm** [comment]
Problèmes résolus

**Comment by massimotisi** [comment]
Please do not modify CACAO2017/src/abstraction/transformateur/usa/TransformateurUsa.java and CACAO2017/src/presentation/FenetreJournal.java

**Comment by massimotisi** [comment]
After accepting the pull request from @CACAO2017/transformateur-usa, this one conflicts. Please update from my repository and solve the conflict.

**Comment by theostourm** [comment]
is it good ?

**Comment by massimotisi** [comment]
@CACAO2017/transformateur-europe: 
- After accepting the other pull requests, this one conflicts. Please update from my repository and solve the conflict.
- Then check the files you are sending in this pull request: https://github.com/CACAO2017/CACAO2017/pull/57/files 
- You are changing the file `CACAO2017/.gitignore`, this is not allowed
- You are removing some spaces from the files of @CACAO2017/distributeur-europe, this is not allowed without the OK of @CACAO2017/distributeur-europe

**Comment by massimotisi** [comment]
@theostourm: in case you have troubles finding the `.gitignore` file, you can edit it directly online on your repository: https://github.com/theostourm/CACAO2017/blob/master/.gitignore

**Comment by massimotisi** [comment]
Is this pull request ready?

**Comment by theostourm** [comment]
I don’t understand but everything my group had done was received by you, and now all is fine.Le 1 juin 2017 à 10:11, Massimo Tisi <notifications@github.com> a écrit :Is this pull request ready?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CACAO2017/CACAO2017","title":"CACAO2017/CACAO2017","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CACAO2017/CACAO2017" class="">https://github.com/CACAO2017/CACAO2017</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@massimotisi in #57: Is this pull request ready?"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/CACAO2017/CACAO2017/pull/57#issuecomment-305422053" class="">https://github.com/CACAO2017/CACAO2017/pull/57#issuecomment-305422053</a>"}}}

**Comment by theostourm** [comment]
Can we close this pull request and do another one ?

**Comment by massimotisi** [comment]
The pull request looks ok from my side but you should have notified me right after you finished fixing it. I am merging it.

**Pull request merged**
