### PR TITLE
Marche harmonisation

### PR DESCRIPTION
**Pull request by wowalid**

### CODE REVIEW

**Comment by massimotisi** [comment]
You are changing a file from @CACAO2017/transformateur-usa.

**Comment by wowalid** [comment]
done

**Comment by massimotisi** [comment]
Nothing changed. Either you remove your change or I need the OK from @CACAO2017/transformateur-usa

**Comment by massimotisi** [comment]
After accepting the pull request from @CACAO2017/transformateur-usa, this one conflicts. Please update from my repository and solve the conflict.

**Comment by wowalid** [comment]
sorry its ok now

**Comment by massimotisi** [comment]
Your code raises a runtime exception: `Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException`

**Comment by wowalid** [comment]
it should be ok now

**Pull request merged**
