### PR TITLE
Changenamepackage

### PR DESCRIPTION
**Pull request by antoineroson**
Change name to abstraction.role.country

### CODE REVIEW

**Comment by massimotisi** [comment]
refusing because you are adding an empty line to `CACAO2017/src/abstraction/fourni/v0/Producteur.java`

**Comment by antoineroson** [comment]
The line was added and deleted.

**Comment by antoineroson** [comment]
sorry ! I can't find the added line

**Comment by massimotisi** [comment]
Sorry it's not an added line, you have added some spaces on line 46.
You can see your changes here: https://github.com/CACAO2017/CACAO2017/pull/18/files

**Comment by antoineroson** [comment]
hope it's fine like that

**Pull request merged**
